python.home=C:/Users/user/AppData/Local/Python/pythoncore-3.14-64
python.executable=C:/Users/user/AppData/Local/Python/pythoncore-3.14-64/python.exe
python.library=C:/Users/user/AppData/Local/Python/pythoncore-3.14-64/python314.dll
jpy.library=C:/Users/user/AppData/Local/Python/pythoncore-3.14-64/Lib/site-packages/jpy.cp314-win_amd64.pyd
jdl.library=C:/Users/user/AppData/Local/Python/pythoncore-3.14-64/Lib/site-packages/jdl.cp314-win_amd64.pyd
database.path=Data/java_linkedin_sandbox/jobs.sqlite
raw.directory=Data/java_linkedin_sandbox/raw/linkedin
profile.directory=Data/browser_profiles/linkedin
